using FluentValidation;
using SimpleCleanArch.Application.DTOs;

namespace SimpleCleanArch.Application.Validators
{
    public class KeywordDtoValidator : AbstractValidator<KeywordDto>
    {
        public KeywordDtoValidator()
        {
            RuleFor(x => x.Word)
                .NotEmpty()
                .WithMessage("Word is required")
                .MaximumLength(100)
                .WithMessage("Word cannot exceed 100 characters");

            // We don't need to validate Id for new keywords
            // The Id will be generated by the database
        }
    }
} 